[package]
name = "mapper_service"
version = "0.0.1"
authors = ["Tomáš Diblík <dibla.tomas@post.cz>"]
edition = "2021"
description = "TODO"
license-file = "../LICENSE"

[profile.release]
opt-level = 3

[dependencies]
winapi = { version = "0.3.9", features = ["winuser", "libloaderapi"] }
anyhow = "1.0.69"

[build-dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html